### ISSUE TITLE
Cursor not visible in highlighted lines

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#148] opened 2018-05-12 23:46 UTC
really - it's a pain in the ass :P  Example:

https://salsa.debian.org/lxqt-team/libfm-qt/blob/debian/sid/debian/libfm-qt3.symbols 

please edit the arches in these lines
```
 (c++|arch=  armel riscv64 )"vtable for std::_Sp_counted_ptr_inplace<Fm::IconInfo, std::allocator<Fm::IconInfo>, (__gnu_cxx::_Lock_policy)1>@Base" 0.12.0
 (c++|arch=  armel riscv64 )"typeinfo name for std::_Sp_counted_ptr_inplace<std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> >, std::allocator<std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > >, (__gnu_cxx::_Lock_policy)1>@Base" 0.12.0 
 (c++|arch= !armel !riscv64 )"typeinfo name for std::_Sp_counted_ptr_inplace<Fm::BookmarkItem const, std::allocator<Fm::BookmarkItem>, (__gnu_cxx::_Lock_policy)2>@Base" 0.12.0 
```
one will normally search without the brackets part - so when i search a line like
```
"typeinfo name for std::_Sp_counted_ptr_inplace<std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> >, std::allocator<std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > >, (__gnu_cxx::_Lock_policy)1>@Base" 0.12.0
```
the whole line will be highlighted - please search the cursor in the line if you want to edit :D

**Comment by tsujan** [comment] 2018-05-13 02:09
I didn't understand your point.

When you search that string, it'll be both selected and highlighted inside the text. If the text-view does not have focus, there will be no blinking cursor but the user knows that, with a selection, the cursor is always at the end. However, it you focus the text-view by right-clicking and closing the context menu, you'll the the blinking cursor.

**Comment by tsujan** [comment] 2018-05-13 02:11
The selection color of the Qt theme you use has also a role. As you can see in the following screenshot, everything is visible enough, including the cursor (which is blinking):

![screengrab-20180513-064001](https://user-images.githubusercontent.com/981076/39963139-a54fe774-5678-11e8-92cc-1cad4c8bf85b.png)

**Comment by tsujan** [comment] 2018-05-13 04:50
Aha, I got your point! You don't mean the selected text but the highlighted one when it matches the searched text. Yes, the cursor visibility is low and should be corrected.

**Comment by agaida** [comment] 2018-05-13 08:59
right - normally one don't search for such long stings - but with symbols one will do

**Comment by tsujan** [comment] 2018-05-14 14:14
Done in https://github.com/tsujan/FeatherPad/commit/7437800022a94bde428839f665658b15e033b47e by using a different match highlighting but it can be really solved by using "thick cursors".

The problem is deep inside Qt.

**Closed by tsujan** 2018-05-14 14:14 UTC
