### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by ozky** [tsujan/FeatherPad#11] opened 2016-12-03 17:14 UTC
Featherpad open text files in new window not in new tab,i need to use file menu to open it in new tab but why it's doing it. ? 
Sometimes it open text files in new tab like it should be so there have to be some bug in somewhere.

**Comment by tsujan** [comment] 2016-12-03 17:19
(1) Which version do you use? The latest git?

(2) Which window manager do you have? KWin, OpenBox,...?

(3) Has FeatherPad crashed before? I ask because if it has crashed, the next time, new files will be opened in new windows but the time after that, it should work OK. If any crash has happened, I'd be grateful if you tell me how to reproduce it or give a backtrace.

**Comment by tsujan** [comment] 2016-12-03 17:25
I forgot to ask a forth question:

(4) Which file manager do you use? Dolphin, pcmanfm-qt, Nemo,....?

**Comment by tsujan** [comment] 2016-12-03 18:21
@ozky 
Are you sure you haven't mistaken a feature (Desktop awareness) with a bug?

**Comment by ozky** [comment] 2016-12-04 06:48
Pcmanfm-qt and openbox with lxqt and it have none crash on my system.

**Comment by tsujan** [comment] 2016-12-04 08:19
> Featherpad 0.5.8 pcmanfm-qt and openbox with lxqt and it have none crash on my system.

OK! Then, there should be no issue.

Let's be more specific. FeatherPad is "desktop aware", which means that if you open files in Desktop1, for example, they will be opened as new tabs and if you go to Desktop2, the next file will be opened in a new window but, after that, other files will be opened as new tabs in that window. And so on.

Now, if you see the above behavior, it's a *feature*. FeatherPad contains a lot of code for it. In short: *files from each desktop are opened as new tabs in a window on that same desktop.*

If you see another behavior, please describe it specifically!

**Comment by ozky** [comment] 2016-12-04 08:45
Ok i only use one virtual desktop. Here is this behavor i open featherpad from lxqt menu then open text file 1 it will open it then mouse click from pcmanfm-qt,second text file it open it in new window same time openbox have setting 1 virtual desktop.

**Comment by tsujan** [comment] 2016-12-04 09:16
Very strange! I switched to openbox with the same setting and still can't reproduce this issue:

![openbox](https://cloud.githubusercontent.com/assets/981076/20865143/66dc8912-ba1f-11e6-83f4-6eed33dda0e1.png)

Could you please close all FeatherPad windows and run FeatherPad from terminal (by entering `featherpad` in it) and see if there is any message?

**Comment by ozky** [comment] 2016-12-04 11:41
Only it complain xcb some errors can this bug be in lxqt ? it seems that lxqt right click desktop menu do it.
`featherpad
QXcbConnection: XCB error: 3 (BadWindow), sequence: 731, resource id: 12602110, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 940, resource id: 12602239, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1215, resource id: 12602368, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1638, resource id: 12602627, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2065, resource id: 12602755, major code: 40 (TranslateCoords), minor code: 0`

**Comment by tsujan** [comment] 2016-12-04 12:02
Interesting! The problem is not in FeatherPad. No crash has happened. But there's something seriously wrong with Qt's xcb plugin. That may have different causes. For example, your installed version of qt5-x11extras (libqt5x11extras5 in Debian/Ubuntu) may be different from that of qt5-base (qtbase5 in Debian). Or your installed LXQt may have an issue.

I guess this is a recent problem that happened after an update. Am I right? If so, you could try to recompile FeatherPad (its latest GitHub version). Which Linux distro do you use and what are the version of Qt5 and LXQt on your system?

Anyhow, I may add an option to FeatherPad for disabling "desktop awareness" -- although I've tested it on Debian, Ubuntu, OpenSUSE, Arch/Manjaro and even FreeBSD with various Desktop environments. But I have to think about that.

**Comment by ozky** [comment] 2016-12-04 12:16
I use Mageia 6 sta2 lxqt 0.11 and it's packager of featherpad is Yochenhsieh.

**Comment by ozky** [comment] 2016-12-04 12:19
You were right i recompiled Mageia src.rpm and it don't complain anymore those xcb errors.

**Comment by tsujan** [comment] 2016-12-04 14:39
I'll look into Mageia's `src.rpm`. In the meantime, could you test Mageia's FeatherPad outside Mageia's LXQt and with a file manager other than Mageia's pcmanfm-qt? And did you check the versions of qt5-x11extras and qt5-base?

**Comment by tsujan** [comment] 2016-12-04 15:56
I looked into Mageia's `featherpad-0.5.8-1.mga6.src.rpm`. It's completely good.

I'm still curious why files are opened in new windows instead of new tabs in your case. So, I wait for your test under another desktop environment and with another file manager.

**Comment by ozky** [comment] 2016-12-05 06:54
Same behavor with gnome-shell and mate and other desktops.

**Comment by ozky** [comment] 2016-12-05 07:05
Also qt5-x11extras qt5-base is same version 5.6.2.

**Comment by tsujan** [comment] 2016-12-05 08:27
> Same behavor with gnome-shell and mate and other desktops.

Good! That's quite a step toward finding the cause.

Do you see *two* "featherpad" processes in those cases that *two* windows are opened? You could easily investigate that by using a system monitor like gnome-system-monitor or ksysguard

**Comment by ozky** [comment] 2016-12-05 16:30
No there is only one instance running in mate system monitor same time.
I also found new info it do it when i open first file from featherpad menu and second one from desktop file manager.
Bit late answer i did need to watch floorball as there is world champions going on. :D

**Comment by tsujan** [comment] 2016-12-05 18:05
If there's only one instance, I really have no clue because I can't reproduce the issue.

I our investigation, there was a question you didn't answer: Did this happen always or did it start after an update/upgrade?

**Comment by tsujan** [comment] 2016-12-05 18:24
In addition to the above question, I'd have another request that may shed light on this situation:

Could you compile the latest GitHub version and try it without installation? It's enough to do a `qmake && make` in a terminal opened inside the source folder and then run the executable "featherpad" inside the "featherpad" folder. Please close all FeatherPad windows, run that executable and see if the the problem happens with it too.

**Comment by tsujan** [comment] 2016-12-05 18:37
Sorry, my last suggestion will have meaning only if you install the new version with `sudo make install` (because of the nature of the problem)!

**Comment by tsujan** [comment] 2016-12-05 19:23
Ignore my last suggestion! The latest GitHub version shouldn't make a difference in this regard. The mystery remains!

**Comment by ozky** [comment] 2016-12-06 08:48
No it was not start upgrade as featherpad is 0.9.8 installed without upgrade from older release.
I always reset all programs what i use to defaults avoid problems when upgrade it.

**Comment by tsujan** [comment] 2016-12-06 10:10
Since I can't reproduce this issue, I completely rely on your tests.

If I have understood correctly, this is what happens for you: You run FeatherPad and open a file with its "File" menu; then you click on a file and it opens in a new window. What if you *drag and drop* that file into the FeatherPad window instead? Does it still open in a new window?

**Comment by ozky** [comment] 2016-12-06 18:37
No it opens only new tab.

**Comment by tsujan** [comment] 2016-12-06 21:22
A second window will be opened only if, at least, one of these three conditions is satisfied:

(1) The file is opened from another desktop;
(2) The first window has a dialog; or
(3) The first window is off the available screen geometry.

Now, the first condition can be riled out because there's only a single desktop in your case. Your last test rules out the second condition too. Therefore, from the information you gave me, I logically conclude that Qt doesn't get the desktop and/or window geometry correctly in your case. If you have a 4k or HDPI (very high resolution) monitor, that's expected because Qt5 has an unresolved bug related to that. If not, there should be a problem in the x11 support of your Qt5 installation.

Please see that the above conclusion is based on the available information; further data might shed more light on this issue.

**Comment by tsujan** [comment] 2017-04-26 03:08
Closing this because neither I nor anyone else could reproduce this. Feel free to reopen if it still occurs with the latest version on an up-to-date Linux distro!

**Closed by tsujan** 2017-04-26 03:08 UTC

**Comment by pirate486743186** [comment] 2020-04-27 18:01
rehello tsujan...

i ran into the same problem as this user. After quite bit of searching, i read in the manual, that if the window is too offscreen, it opens a new window....-_-

This is exactly the problem i was complaining about with lximage. These features are breaking usual conventions and users get confused.

At first, i simply saw files open new windows or new tabs at random. Only, after a lot of testing, i figured, that been too far offscreen or minimized would launch a new window... And even then, i assumed it was a bug....

The user above, didn't read the manual. Like me, it didn't crossed his mind that this was a feature....

**Comment by tsujan** [comment] 2020-04-27 18:18
> i figured, that been too far offscreen...

If they are very offscreen, a new window will be opened. That's intentional.

> These features are breaking usual conventions

Depends on your interpretation of "usual conventions". If I was happy with how other text editors worked, I wouldn't make FeatherPad.

**Comment by mistwalletleech** [comment] 2024-07-24 01:11
This is happening on Lubuntu LTS 24.04. If Featherpad is minimized, it will open files in a new window instead of a new tab. This is on the same desktop. I'm not sure this really matches the "desktop awareness" mentioned in this thread. Does featherpad being minimized count as a different desktop?

**Comment by tsujan** [comment] 2024-07-24 10:11
>  If Featherpad is minimized, it will open....

→ https://github.com/tsujan/FeatherPad/releases/tag/V1.5.1
