### ISSUE TITLE
The color theme is no longer syncing with system themes

### ISSUE THREAD

**Issue by phollox-arch** [tsujan/FeatherPad#645] opened 2022-05-10 20:51 UTC
I installed Featherpad back in version 0.18. I have LXQt configured for dark mode, and dark themes. Featherpad recognized this colors and matched all my other apps, except after update to 1.2. Downgrading to 1.1.1 makes that this dark color still works. Not sure what's the source of the problem

**Comment by tsujan** [comment] 2022-05-10 20:58
Duplicate of https://github.com/tsujan/FeatherPad/issues/640. Please read my reply there.

Like KDE, LXQt doesn't support Qt6 styling yet. So, Qt6 apps aren't style-aware.

**Closed by tsujan** 2022-05-10 20:58 UTC
