### ISSUE TITLE
Feature request: Preserver search history over a bunch of files

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#289] opened 2019-07-16 22:27 UTC
Use case: I'm about to edit n Files - and have to replace the same things in every file. Example

![](https://i.imgur.com/AQMy5tO.png=)

Before you say: Just use sed - no, there are often cases that are not so trivial :rofl:

**Comment by agaida** [comment] 2019-07-16 22:31
Before i forget: same for search and replace history :)

**Comment by tsujan** [comment] 2019-07-16 22:50
Replace strings are for all tabs because there's only one replacement dock, so there's nothing to do for it.

But, contrary to appearances, there's one search entry for each tab. About 2-3 years ago, all tabs had the same search entry but that was sub-optimal for various reasons. When you change the tab, you'll see another search entry, although identical in shape.

I think you mean an option to preserve the search string on switching tabs. Otherwise, it's impossible to share search histories between multiple line-edits.

**Comment by tsujan** [comment] 2019-07-16 22:52
Wait a minute! You want to replace the same things in all files? Well, it's a piece of cake because the replacement dock is shared.

I think there may be a misunderstanding here.

**Comment by agaida** [comment] 2019-07-16 23:01
i only tried search - and not replace - reason: when i only edit 3 or 4 files i mostly use search. :) Not tried s/r. For the other thing just checkout pcmanfm-qt and 
```
grep -rl Alt+Enter | xargs fpad
```
and yes - i guess i want preserving the search string on switching tabs - and if more than one string is to search for i want the history :D

**Comment by tsujan** [comment] 2019-07-16 23:09
This is more complex than it seems. I might need to talk with you about it later.

P.S. My brain is overclocked by the problem in MTP DND of pcmanfm-qt (I know the solution but not why it's a solution); so, for now, I can't form a clear idea about this ;)

**Comment by tsujan** [comment] 2019-07-25 22:10
Sorry for the delay!

In old times, FeatherPad had a single search entry, whose text was changed when the active tab was switched. Then, I saw the need for search history (I think you proposed it). It wasn't possible with a single search entry — you can't make up search histories for all tabs and give them to a single search entry — so, I made each tab have its own search entry. That design was superior to the previous one in other regards too. It made me restructure the code.

Restoring the single search entry would be a regression. Making it optional at start-up causes complications. Making it optional on-the-fly means a great amount of unmaintainable code.

For now, I see no beautiful solution. Replacing a single string in all tabs is very easy because the replacement dock is shared by all of them. Searching a single entry needs pasting it into all search entries. However, I keep this report open because, who knows, a new idea may suddenly come to my mind — or your mind.

**Comment by agaida** [comment] 2019-07-25 22:16
No problem - but something like that would be help a lot, esp. when one is refactoring things, Maybe it is worth to have a look at other editors.

**Comment by tsujan** [comment] 2019-07-25 22:36
> Maybe it is worth to have a look at other editors.

An *extra* search entry can be added, so that it's shared by all tabs. Doing that is easy. What's not easy is keeping FeatherPad's GUI as simple as it is now. A look at the mess in Kate's GUI is enough for me to run away ;)

I should find a way of adding a shared search entry in such a way that it doesn't damage the current GUI. When it "pops up", all tab-specific search entries should disappear and new tabs shouldn't have specific search entries. When it's disabled, the opposite should be done....

**Comment by agaida** [comment] 2019-07-25 22:42
Sounds cool - and can you please review https://github.com/lxqt/liblxqt/pull/223#issuecomment-515089961

**Comment by tsujan** [comment] 2019-07-25 22:44
> review lxqt/liblxqt#223 (comment)

I will, tomorrow.

I guess this feature will be for V0.12.0. V0.11.0 will be ready for release soon; I want to keep it stable, with its new spell checker and other things.

**Comment by agaida** [comment] 2019-07-25 23:06
Please no hurry - there are reasons to make stable software ...

![image](https://user-images.githubusercontent.com/1162845/61914592-64c6dc80-af41-11e9-9953-883261b0deb9.png)

**Comment by tsujan** [comment] 2019-07-26 09:31
Yes, you had shown me the link. It's a result of both your Debian support and your several ideas like this one.

**Comment by agaida** [comment] 2019-07-26 09:53
Far more important - it clearly shows the debian mentality - some users use sid and testing (Featherpad was not in stable before) - but the vast majority of the users prefer stable with all pro's and con's - and they have trust in that the software is in a well tested and usable state. The pragmatic approach :smile:

**Comment by tsujan** [comment] 2019-07-26 12:41
NOTE:

Today, I started to see the following announcement whenever I sign into GitHub:

*"Due to U.S. trade controls law restrictions, your GitHub account has been restricted. For individual accounts, you may have limited access to free GitHub public repository services for personal communications only...."*

I've disliked politics and politicians since childhood —  yes, childhood, not adolescence ;) — and, living in Iran, I've been successful in defending my private life as an individual from their influence (believe me, it isn't easy in Iran but I've been successful). Now, the U.S. government wants to affect it!

I don't know whether GitHub's announcement is just a formality or will prevent me from coding in GitHub — in the fist case, it's ugly; in the second case, I might try GitLab, although it might do the same thing ;) — but, for now, I can make PRs and do all things I usually do with GitHub.

I just wanted to say that if I "disappeared" suddenly, I'm still alive and will be active in another way. If that happens, I think I could leave a note here. Hopefully, it won't happen.

**Comment by agaida** [comment] 2019-07-26 14:23
In case we can switch to our git.lxqt.org and only use github as a mirror - or set up a bidirectional sync.

And writing a nice letter from Germany, content: "Fuck you, Github" in some nicer words.
And maybe go to the press with it, should be no problem if one has friends that are writers ...

**Comment by tsujan** [comment] 2019-07-26 14:35
> In case we can switch to our git.lxqt.org

GitHub hadn't blocked me yet.

> You can call me a bit neurotic, but i have no faith in things that i can't control

Like you, I don't have faith in things that are out of my control but I'm calm because that was hardly a surprise to me. Logic was discovered by Socrates and Aristotle 2500 years ago, at last, but two groups never heard anything: politicians and religious people. I know these things first hand ;)

Let's wait to see what will happen. Madness may have not limit but, sometimes, it can be a little entertaining to watch it from a safe distance.

**Comment by tsujan** [comment] 2019-07-26 14:52
Oh, I forgot to attach a beautiful screenshot; I should do it before they "kill" me:

![politics](https://user-images.githubusercontent.com/981076/61960396-99d33d80-afda-11e9-8bd3-cd7a6b6feacc.png)

**Comment by tsujan** [comment] 2019-07-27 15:47
Ha ha! I took a look at github page source and found that ugly announcement at the bottom, under:

```css
<div class="flash flash-full js-notice flash-warn">
```

So, I added this stylesheet to Falkon and got rid of it:

```css
div[class*="flash flash-full js-notice flash-warn"] {
display: none;
}
```

**Comment by tsujan** [comment] 2019-08-10 19:38
@agaida 

Off topic again but it occupied my mind today:

Do you think highlighting the syntax of a document with more than 20,000 lines makes sense?

**Comment by agaida** [comment] 2019-08-10 19:41
of course it make sense - optional

**Comment by tsujan** [comment] 2019-08-10 19:47
Then, I should rewrite the syntax highlighting code from start :( With some syntaxes, more than 20,000 lines means a lot of CPU usage.

Kate  makes a trick in such cases but I don't know what it is. It should be hidden somewhere in KDE's syntax highlighting library. Or maybe, I should make FeatherPad depend on `KSyntaxHighlighting` if it's tier-one (don't like that at all) or include its code instead. A lot of headache, today ;)

**Comment by agaida** [comment] 2019-08-10 19:50
headaches - ok, i can help with and make them grow ;P

https://bugs.launchpad.net/ubuntu/+source/featherpad/+bug/1833118

**Comment by tsujan** [comment] 2019-08-10 20:12
> i can help with and make them grow

You can't ;) That's intentional. If FeatherPad highlighted all lines at once, it would take a great amount of CPU time with usual documents. Only the visible part of the document as well as those parts that were visible before have syntax highlighting. So, printing with syntax highlighting would be inconsistent.

**Comment by tsujan** [comment] 2019-08-10 21:36
Everything might change, so I opened https://github.com/tsujan/FeatherPad/issues/294

**Comment by tsujan** [comment] 2019-08-11 14:27
OK, after considering it for 2 days, I think there's no needed to rewrite. FeatherPad highlights more details than Kate and other text editors do. For example, Kate doesn't highlight URLs or email addresses inside comments or quotes, while FeatherPad not only does so but also adds code for opening them. Such details take more CPU time for huge documents.

**Comment by tsujan** [comment] 2019-08-15 20:44
Back to the current feature:

My previous ideas were wrong — I shouldn't think about other things when my mind is busy. 

Implementing a shared search history is so easy. Kate has a shared history by default but I'll add it as an option (that needs app restart).

Later, the shared search history could also be saved — although I think that's an overkill and without real purpose.

**Comment by tsujan** [comment] 2019-08-16 16:55
It's done but not committed yet (I should test it for a while because several difficulties showed up):

![shared_search_history](https://user-images.githubusercontent.com/981076/63184162-f53d9c00-c06b-11e9-801a-add86b6c1319.png)

It's better than Kate's; Kate sometimes changes search texts of other entries when the user presses Enter in one of them.

The history list can be shown by pressing Ctrl+UP/Down while the entry has focus but the items can also be selected without showing it by pressing Up/Down arrow keys.

So, for example, when multiple files are opened, a text can be searched in the first one, then the tab can be switched and the same search text will appear in its entry if Up/Down is pressed, and so on for other tabs. The last searched text is always at the top of the list.

Cool feature. Thanks for telling me about it!

**Closed** 2019-08-18 09:10 UTC
Labels: enhancement
