### ISSUE TITLE
hangup on copying path when recording the file

### ISSUE THREAD

**Issue by pinkie13** [tsujan/FeatherPad#759] opened 2023-08-06 14:02 UTC
I:
- open a recorded file,ok
- click on "Enregister sous",ok
- right click on a file in the list, and choose  "Enregistrer l'emplacement",ok
- Hit ESC,ok
- right click in the text (wanting to paste the path just collected...) ..KO !
-.. Then, Featherpad stop responding: Forced to kill the process ...

Context : 
- Debian bookworm (12), french langage
- FeatherPad 1.3.5

This happen with any file opened ..

**Comment by tsujan** [comment] 2023-08-06 16:56
Thanks for caring and reporting!

> right click on a file in the list, and choose "Enregistrer l'emplacement",ok...

You probably mean copying a file and pasting it into FeatherPad (Preferences -> Files -> Paste paths instead of files). That has changed in the latest version 1.4.1, although FeatherPad didn't hang before 1.4.1 either (if the file is huge, you might need to wait).

Your report made me find a small problem regarding file pasting in 1.4.1 too. I'll investigate it soon, but since it isn't about any hang, I'm closing this. If you see the hang with 1.4.1 and can provide a way of reproducing it, please tell me to reopen the report.

**Closed by tsujan** 2023-08-06 16:56 UTC

**Comment by tsujan** [comment] 2023-08-06 17:01
Oh, fortunately, the small problem I found wasn't in 1.4.1 (latest release) but in git. 1.4.1 is OK.

**Comment by pinkie13** [comment] 2023-08-07 17:57
> You probably mean copying a file and pasting it into FeatherPad ...
Sorry, not at all ! I tried to paste the pathname of a file, not the
file itself ! :o)
-- 
francis Wong
