### ISSUE TITLE
Crash while trying to paste text from empty primary clipboard

### ISSUE THREAD

**Issue by josefbachmann** [tsujan/FeatherPad#681] opened 2022-10-07 11:58 UTC
Hi
Does anyone else have this problem?

- Arch Linux
- Kernel 5.19.13
- Featherpad 1.3.2

If the primary clipboard (wl-clipboard in my case) is empty, Featherpad **crashes** when trying to paste clipboard content: **Segmentation fault (core dumped)**

How to reproduce

1. Open Featherpad
2. Open Linux Terminal and run `wl-copy --primary --clear` 
3. Ctrl+V in Featherpad

Greetings

**Comment by tsujan** [comment] 2022-10-07 17:21
Thanks for the report!

**Comment by tsujan** [comment] 2022-10-07 18:23
Fixed in https://github.com/tsujan/FeatherPad/commit/f05c72a79ea8f14991d68dd3ebda5c331a786549

I'll release 1.3.3 soon.

**Closed by tsujan** 2022-10-07 18:23 UTC
Labels: bug

**Comment by josefbachmann** [comment] 2022-10-07 23:49
That was fast. Thanks a lot for the outstanding work!

**Comment by tsujan** [comment] 2022-10-08 00:04
You're welcome, and thanks again for telling me about the crash!

I think most users — me included — have a habit of pasting only after copying. Apparently, you were the first user who encountered this nasty crash (whose root cause was in Qt itself).

V1.3.3 has been released. It should appear in Arch soon.
