### ISSUE TITLE
Mac OS experience

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#221] opened 2018-12-31 10:09 UTC
<img width="812" alt="image" src="https://user-images.githubusercontent.com/19782228/50557924-277bd280-0d03-11e9-981c-7f123a39ea2e.png">
As you were suddenly interested in Mac OS experience, that's what I've got here.
I built the project without any single change. Everything works well when build in a dedicated directory, but make install fails:

```
MacBook-Pro-Pavel:FeatherPad pavel$ sudo make install
Password:
cd featherpad/ && ( test -e Makefile || /Users/pavel/Qt/5.12.0/clang_64/bin/qmake -o Makefile /Users/pavel/ITprojects/FeatherPad/featherpad/featherpad.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile install
rm -f -r /usr/bin/featherpad.app
/Users/pavel/Qt/5.12.0/clang_64/bin/qmake -install qinstall featherpad.app /usr/bin/featherpad.app
Error copying featherpad.app/Contents/MacOS/featherpad to /usr/bin/featherpad.app/Contents/MacOS/featherpad: Cannot create /usr/bin/featherpad.app/Contents/MacOS/featherpad for output
make[1]: [install_target] Error 3 (ignored)
ln -sf featherpad fpad && cp -P fpad /usr/bin
cp: fpad: No such file or directory
```
Thus, I cannot test help pages and translations
P. S. Mac OS Mojave 10.14.1 , Qt 5.12.0
```
clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
```

**Comment by tsujan** [comment] 2018-12-31 10:31
> As you were suddenly interested in Mac OS experience...

I've been interested in it since a while because a user of this or another project of mine asked about the Mac support and I said I couldn't do anything. Happy to know that it compiles on Mac :)

> but make install fails:

That's unfortunate. It means still no Mac support :( There was a similar problem on Haiku OS but it was fixed by a Haiku user. Do you think this can be fixed in a similar way?

**Comment by shlyakpavel** [comment] 2018-12-31 10:36
> That's unfortunate. It means still no Mac support :( There was a similar problem on Haiku OS but it was fixed by a Haiku user. Do you think this can be fixed in a similar way?

I believe the problem is quite easy to fix. I will dig into it later.

**Comment by tsujan** [comment] 2018-12-31 10:42
It'll be very nice if Mac is also supported. Forget about translations; they aren't important. Also, I don't expect that virtual desktop awareness works on Mac; such properties aren't essential. But, for example, syntax highlighting and session management are important.

**Comment by tsujan** [comment] 2018-12-31 10:47
BTW, if you fix it -- and I really don't want to bother you with it (I mean it!) -- I could use your method in other projects.

**Comment by shlyakpavel** [comment] 2018-12-31 16:42
For the app icon:
The only correct way to set app icon on Mac is putting 

`ICON = iconset.icns`

into the project file. However, I do not like the idea of putting one more icon in the repo.
The hack I've tried is:
```
qlmanage -t -s 1000 -o . ./featherpad/data/featherpad.svg
iconutil --convert icns path-to-pngs/
```
Works on poor Mac OS. The first line gets png out of svg. The second one - icns out of a set of pngs. Scripting this altogether would enable app icon support.
I really wonder why Qt devs didn't bring all of this in qmake...

**Comment by tsujan** [comment] 2018-12-31 17:40
> Have left a const QString hack in main.cpp in order to workaround this

Would you please leave translation to a second PR and remove that `const QString` for now? Either the problem shouldn't be fixed by a `const QString` or we should know what really happens. That could be discussed/experimented in a separate PR.

**Comment by shlyakpavel** [comment] 2018-12-31 17:42
@tsujan already done in the PR

**Comment by tsujan** [comment] 2018-12-31 17:44
Oh, sorry! The comment to which I replied was written 5 hours ago and I was so drowsy ;)

**Comment by tsujan** [comment] 2018-12-31 17:57
I merged your PR as it was. Looking forward to your next PR(s) for a complete Mac support -- whenever you find the best solution(s).

And sorry that I can't be of help on Mac icons -- my knowledge of Mac OS is very poor.

**Comment by tsujan** [comment] 2019-01-06 06:45
> Why do you assume...

Will look into it later -- I don't remember now (working on pcmanfm-qt's Desktop and some aspects of FeatherPad...).

> I am not sure if this is also working properly.

It does work, because of `tr()`.

**Comment by shlyakpavel** [comment] 2019-01-06 07:33
> It does work, because of `tr()`.

Have checked this, you're right, it works.. So the whole problem is basically in `!txt.contains ("+")`
Shotcuts are also displayed incorrectly now, but this is not a big deal

**Comment by shlyakpavel** [comment] 2019-01-06 08:31
> > Why do you assume...
> 
> Will look into it later

Is is reinventing [QKeySequence::count](http://doc.qt.io/qt-5/qkeysequence.html#count) function. The code checks if string contains "+" to know if there are multiple keys. QKeySequence::count > 1 is practically the same, but more platform-independent

**Comment by tsujan** [comment] 2019-01-12 14:12
I investigated it.

> The code checks if string contains "+" to know if there are multiple keys. QKeySequence::count > 1 is practically the same...

No! `QKeySequence::count`gives the number of shortcuts. Here, I want to prevent entering of "A", "Z" , "9", "Tab", "Backspace" and so on -- because this is a text editor.

> Why do you assume it to contain "+"?

"+" is correct. It is used in "qkeysequence.cpp" → `addKey()`, which is used by `QKeySequencePrivate::encodeString` for everything other than Mac + `NativeText`, while the output is always `PortableText`.

**Comment by tsujan** [comment] 2019-01-12 14:13
That being said, a revision is needed because some Fx shortcuts should be allowed (although most of them are preserved).

**Comment by tsujan** [comment] 2019-01-12 14:38
A question: Which shortcut had you entered in the screenshot of https://github.com/tsujan/FeatherPad/issues/221#issuecomment-451718848 ?

**Comment by shlyakpavel** [comment] 2019-01-12 14:42
> A question: Which shortcut had you entered in the screenshot of [#221 (comment)](https://github.com/tsujan/FeatherPad/issues/221#issuecomment-451718848) ?

@tsujan command+T (alt+T on non-mac keyboard)

**Comment by shlyakpavel** [comment] 2019-01-12 14:43
> > The code checks if string contains "+" to know if there are multiple keys. QKeySequence::count > 1 is practically the same...
> 
> No! `QKeySequence::count`gives the number of shortcuts. Here, I want to prevent entering of "A", "Z" , "9", "Tab", "Backspace" and so on -- because this is a text editor.

Did not you read qt documentation? :(
http://doc.qt.io/qt-5/qkeysequence.html#count

**Comment by shlyakpavel** [comment] 2019-01-12 14:45
The **only** correct way to implement things is to get rid of `QString`. Qt has QKeySequence class that does all the job

**Comment by tsujan** [comment] 2019-01-12 14:47
Thanks for your reply! A minute ago, I saw that I was wrong about `PortableText` as output. The solution is simple; will add a commit soon.

> Did not you read qt documentation? :(

Qt doc is ambiguous; it's the number of shortcuts. I checked and its was 1 for "Ctrl+Z".

**Comment by tsujan** [comment] 2019-01-12 14:55
> Qt has QKeySequence class that does all the job

As I said above, it does NOT.

Qt has many holes that can be filled in only by reading its source. *Definitely, no programmer could write a rich Qt program just by following Qt doc.*

**Comment by shlyakpavel** [comment] 2019-01-12 14:59
> Qt doc is ambiguous; it's the number of shortcuts. I checked and its was 1 for "Ctrl+Z".

Was shocked...
```
#include <QKeySequence>
#include <iostream>
int main(int argc, char *argv[])
{
    QKeySequence seq(Qt::CTRL + Qt::Key_Z);
    std::cout << seq.count() << seq.toString(QKeySequence::PortableText).contains('+');
}
```
Outputs 1 1 on Mac....

**Comment by tsujan** [comment] 2019-01-12 15:03
Qt doc is indispensable as a reference but not 100% reliable. Qt code speaks for itself though.

**Comment by tsujan** [comment] 2019-01-12 15:05
My simple solution is converting "native" to "portable" with:
```c++
QKeySequence (txt).toString()
```
Then, even on Mac, that "+" should show up :)

**Comment by shlyakpavel** [comment] 2019-01-12 15:19
> My simple solution is converting "native" to "portable" with:
> 
> ```c++
> QKeySequence (txt).toString()
> ```
> 
> Then, even on Mac, that "+" should show up :)

Looks crazy.. But I believe it works :) Mention me as soon as it needs testing)

**Comment by tsujan** [comment] 2019-01-12 16:45
Update:

Usual ways of saving shortcuts, that can be found here and there on the Internet and also in Qt examples, are inefficient because they use the native format. Even on the same OS, like Linux, the native format works only with the language, in which shortcuts are saved. The user may change language or a global root config (for all languages) may be provided by distro maintainers.

As a test, I chose German, added a custom shortcut -- that worked with German -- and restarted FeatherPad into English: the shortcut wasn't "understood" and so, was deleted.

So, an overhaul is needed.

**Comment by tsujan** [comment] 2019-01-13 09:40
Cleaned up the mess in https://github.com/tsujan/FeatherPad/commit/2a2ccbc29ec61a1c6a585e99921dfdab64236757

Now, it should work in the same way with all languages and on Mac too. Please test!

**Comment by shlyakpavel** [comment] 2019-01-13 10:20
> Now, it should work in the same way with all languages and on Mac too. Please test!
Works fine!
Would be good to land the same to Feathernotes
The last and the only issue with Mac is the app icon. I'll work on it later :)

**Comment by shlyakpavel** [comment] 2019-01-13 10:47
Suddenly got
`2019-01-13 13:46:17.902 FeatherPad[5710:284452] Bad cursor rect event, flags = 0
`
on stdout. Idk what it means and if I should be aware of it

**Comment by tsujan** [comment] 2019-01-13 11:01
> Works fine!

Thanks for testing it!

> #229 would be also a nice-to-have :)

Will see it later.

> Suddenly got... Idk what it means

I've never seen it here. I don't think it's caused by FeatherPad because the message doesn't say anything about Qt.

**Comment by shlyakpavel** [comment] 2019-01-15 13:35
It would be nice to switch qmake to use QMAKE_BUNDLE_DATA for help and translations. That could make the `.pro` files clear and improve portability

**Comment by shlyakpavel** [comment] 2019-08-16 08:31
@tsujan
1. Custom shortcuts do not work anymore
2. It asks me to locate Hunspell lib that I cannot select in file dialog
<img width="845" alt="image" src="https://user-images.githubusercontent.com/19782228/63154495-630ca800-c019-11e9-9d0d-a9042e7b194d.png">

**Comment by tsujan** [comment] 2019-08-16 09:10
> custom shortcuts do not work anymore on Mac

I have no macOS. Please be much more specific! None of them works? Some? Which ones and how?

> It would be also nice to be able to build the app without Hunspell support

So many apps rely on Hunspell and you said cmake compilation worked fine on macOS.

**Comment by tsujan** [comment] 2019-08-16 09:38
As for custom shortcuts, only the suspicious code block that searched for "+" is removed (it was used to distinguish between single-key and multiple-key shortcuts but isn't needed anymore).

A Hunspell dictionary can be (put) anywhere. Hunspell dictionaries can also be downloaded separately. The important thing is that they should be like:
```
/usr/share/hunspell/en_US.dic
```
i.e., a ".dic" file, which should be accompanied by an ".aff" file (otherwise, it isn't a Hunspell dictionary). That's explained in the tooltip and "WhatsThis".

Under Linux, the search button opens the file dialog inside a pertinent Hunspell folder. Of course, that may not be the case under macOS. However, Hunspell dictionaries are independent of all platforms.

**Comment by shlyakpavel** [comment] 2019-08-16 10:13
> I have no macOS. Please be much more specific! None of them works? Some? Which ones and how?
Didn't work after the first start: I changed shortcuts in settings, but the actual ones remained the same. However, they now work correctly. Idk what it was

**Comment by shlyakpavel** [comment] 2019-08-16 10:19
`cmake --target install` is totally broken here. I'll try to rework it later

**Comment by tsujan** [comment] 2019-08-16 15:08
> Didn't work after the first start:... However, they now work correctly. Idk what it was

Good! Nothing has changed in reading/writing shortcuts from/to the config file. The change is only in the shortcut editor and it's small.

> cmake --target install is totally broken here.

You mean:

```sh
cmake .. -DCMAKE_INSTALL_PREFIX=YOUR_INSTALLATION_DIRECTORY
```

It works here but, of course, you might want to modify the `CMakeLists.txt` files for macOS -- I tried to do the same thing you did in the `pro` file but mistakes are possible. If there is a problem, please tell me or make a PR!

**Comment by shlyakpavel** [comment] 2019-08-17 22:43
>> but mistakes are possible.
cmake puts files to the wrong places. I'll dig into this later

**Comment by tsujan** [comment] 2019-08-18 04:58
> cmake puts files to the wrong places. I'll dig into this later

Yes, please do so! I'm sure only about Linux -- cmake works fine under Linux, with or without custom installation path.

**Closed** 2020-10-01 04:34 UTC
