### ISSUE TITLE
Task bar title sometimes doesn't reflect actual tab title

### ISSUE THREAD

**Issue by fulalas** [tsujan/FeatherPad#36] opened 2017-05-24 23:49 UTC
![title-bug](https://cloud.githubusercontent.com/assets/27843666/26430186/b08e104c-413f-11e7-85a7-0c148a38aa0e.png)

As you can see, although the current tab has the title 'email.txt', the task bar has 'Untitled'. Unfortunately I don't know how to reproduce this bug, but it happens quite frequently.

P.S.: I manually erased other task bar titles.

**Comment by tsujan** [comment] 2017-05-24 23:55
Does the title-bar say 'email.txt' too?

**Comment by tsujan** [comment] 2017-05-24 23:57
Sorry for that question! Yes, of course the title-bar is 'email.txt'. I think this is related to either the window manager you use (OpenBox?) of the task-bar. It can't be caused by FeatherPad or be specific to it.

I close this issue but feel free to add comments -- I'll reply.

**Closed by tsujan** 2017-05-24 23:58 UTC

**Comment by fulalas** [comment] 2017-05-25 00:03
I put the image to illustrate the actual difference between task bar title and FeatherPad title. And sorry, but I'm using LXQt (with OpenBox) for more than 8 months and this bug only happens with FeatherPad.

**Comment by tsujan** [comment] 2017-05-25 00:16
> And sorry, but  I'm using LXQt (with OpenBox) for more than 8 months and this bug only happens with FeatherPad.

No need to be sorry.

As an LXQt developer, I use it too but always with KWin. FeatherPad is responsible for setting the title-bar text, which it does fine. Task-bar is responsible for reading that text and that's completely outside FeatherPad's control.

Why it only happens with FeatherPad, I have no clue but I'm sure this isn't its fault. If I find enough free time, I'll look into LXQt's task-bar code to know how the problem may be caused. I guess it may be related to K Window System.

**Comment by fulalas** [comment] 2017-05-25 01:19
Hmmmm... I understand now. You seem right. :)

I'm trying to reproduce this bug, and the simplest way is to just open/close a simple txt with FeatherPad by double-clicking until the bug happens. You won't need to try this more than 10 times to see it happening.

**Comment by fulalas** [comment] 2017-05-25 01:33
I noticed that sometimes you can see task bar quickly changing from 'Untitled' to the actual name of the text file as soon as you open it. It's weird! Maybe FeatherPad changes its main window title too quickly and task bar gets lost.

**Comment by tsujan** [comment] 2017-05-25 03:41
>  the simplest way is to just open/close a simple txt with FeatherPad by double-clicking until the bug happens.

Oh, that was very informative! This may really be a bug in LXQt task-bar. Tomorrow, I'll think about adding a workaround to FeatherPad and if I find the cause, I'll open an issue at LXQt.

**Comment by tsujan** [comment] 2017-05-25 04:10
Since I can't reproduce this issue, before I do anything, could you please test this:

In file `singleton.cpp`, search for:
```
FPwin* FPsingleton::newWin (const QString& message)
```
and change the place of this line in that function:
```
fp->show();
```
by cutting and pasting it *before*:
```
lastFiles_ = QStringList();
```
Then recompile FeatherPad and see if the issue still happens.

**Comment by tsujan** [comment] 2017-05-25 15:02
Never mind! Even if it worked, it would have side effects.

Among other things, I removed the window title "Untitled" from the ui file (it wasn't needed in the first place). Please test the latest git version!

**Comment by fulalas** [comment] 2017-05-26 06:06
None of the solutions work. :( And, yeah, I didn't combine them.

But then I created a simple QtWidget project from scratch to check if the problem happens, and it doesn't -- no matter how many times I open it, the task bar has always the right title. So I have to conclude that it's probably a FeatherPad bug. Since you're using threads, and these unpredictable issues usually means thread problems, maybe you can try to check it or disable it for testing.

**Comment by tsujan** [comment] 2017-05-26 11:15
> So I have to conclude that it's probably a FeatherPad bug. 

I explained above why it can't be. Take a look at your title-bars! FeatherPad sets their titles correctly. It cannot do the job of LXQt taskbar for it.

**Comment by tsujan** [comment] 2017-05-26 11:32
A more detailed explanation:

On opening a file, FeatherPad first creates an "Untitled" tab and `FPwin::tabSwitch()` sets the window title to "Untitled". Very shortly after that, the file is read in a separate thread and loaded into the same tab. Therefore, the tab and window titles are changed to the file name by `FPwin::addText()` very quickly. This is completely legal.

Now, any window manager should reflect this change, otherwise it would have a bug. *The same is true for any task-bar*. I don't like to change this order in FeatherPad just because LXQt task-bar can't catch a fast change in the window title while the window is being showed. Instead, I prefer to fix the issue in the task-bar itself but currently, I have a very limited free time, which I prefer to spend for my own projects.

**Comment by tsujan** [comment] 2017-05-26 11:45
Opned https://github.com/lxde/lxqt/issues/1303.

**Comment by fulalas** [comment] 2017-05-27 05:31
Thanks for opening the LXQt issue. :)

I created another simple QtWidget project that, each time you press a push button, it changes the window title 1001 time inside a loop. And no matter how many times you press it, there's no problem at all. So I don't think the problem is related to quick change on the window title. As I told you, due to the unpredictable behavior, it's probably related to a thread issue.

**Comment by tsujan** [comment] 2017-05-27 08:13
>  created another simple QtWidget project that, each time you press a push button,

We're talking about changing the title *on showing for the first time*; so your test can't be related to it.

> it's probably related to a thread issue

There isn't such a thing as a "thread issue".
