### ISSUE TITLE
0.9.0 backports fail on Debian Stretch

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#153] opened 2018-05-25 18:14 UTC
With a host of errors, so I assume that it's gcc-6 in Stretch that making the difference from the successful builds in upstream Debian. Is there any "stds=" CXX flag I can give gcc-6 that might fix the problem, or should I try compiling with clang to see if that gets past the error?  I have up to clang-6.0 available in Stretch.
```
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:48:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication:1,
                 from textedit.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:82:22: note: candidate: constexpr QChar::QChar(ushort) <near match>
     Q_DECL_CONSTEXPR QChar(ushort rc) Q_DECL_NOTHROW : ucs(rc) {} // implicit
                      ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:82:22: note:   conversion of argument 1 would be ill-formed:
textedit.cpp:376:36: error: invalid conversion from 'const char*' to 'ushort {aka short unsigned int}' [-fpermissive]
     if (blockText.at (indx - 1) == " ")
                                    ^~~

**Comment by tsujan** [comment] 2018-05-25 18:55
I think the problem is that your installed Qt is too old for FeatherPad.

You could try to change `if (blockText.at (indx - 1) == " ")` to `if (blockText.at (indx - 1) == ' ')` (and the same for similar cases, if any) to see if it can be compiled on Stretch but I think you'll encounter other errors.

Unfortunately, I don't have enough time to support older gcc/Qt versions. However, I'll change that " " to ' ' later -- the latter is better.

**Comment by stevenpusser** [comment] 2018-05-25 19:53
Just patching that one line let a manual build with qmake and make succeed on Stretch; now to try the deb package builds.

Before that, I tried forcing gcc-6 to use a newer std such as c++14 or 17  by adding lines to the pro file as suggested here: https://stackoverflow.com/questions/16948382/how-to-enable-c11-in-qt-creator, but the build output still showed that gcc-6 was still using c++11.

**Comment by tsujan** [comment] 2018-05-25 20:07
Thanks for the info!

Now, the question is: how newer gcc/Qt tolerate that line? I'll investigate that and tell you if I find something.

**Comment by tsujan** [comment] 2018-05-25 21:49
Fixed in https://github.com/tsujan/FeatherPad/commit/93bd3e1b2584cb67a623ceb030917f4129f0a2be

If you keep telling me about such issues in future, I'll try to support Debian Stable as far as possible.

**Closed by tsujan** 2018-05-25 21:49 UTC
