### ISSUE TITLE
Can't change the font in 0.6.2 on the MX 17 Linux alpha Live ISO

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#60] opened 2017-10-27 20:53 UTC
It's just ignoring any attempt to change it, and there's no change in the fp.conf file for the font.  This is a showstopper bug so far...but the same version that has been upgraded to 0.6.2 on an earlier installed version of the alpha has the font changing working.  These were built on straight vanilla Debian Stretch.  Nothing shows up in the terminal when I start featherpad there and try to change fonts--no errors or anything.

Also this comment from a tester:

"The Search feature is what gets me. Cntrl+F for find is ok, but then its F3 for Find Next instead of Ctrl+G. I wouldn't mind, but its apparently one of the key combos you can't change."

Is there any way to switch to the standard Ctl+G?

**Comment by tsujan** [comment] 2017-10-27 21:25
If Preferences → Text → "Remember font" is checked (the default), you might have a permission problem in `~/.config/featherpad`. That could occur if FeatherPad (or another app) is run as root under a DE that doesn't handle root appropriately (of course, FeatherPad *can* be run as root).

> Is there any way to switch to the standard Ctl+G?

I don't know why you think `Ctl+G` is standard -- try Kate, for example. Anyhow, "standard" is a relative term here. `F3` to `F9` are reserved for the search bar and the replacement dock intentionally (they can be memorized easily).

**Comment by tsujan** [comment] 2017-10-27 21:32
BTW, I just checked on 4 distros (Debian, Manjaro, Kubuntu LTS, Fedora), which were installed on 2 computers and VirtualBox, removed FeatherPad-0.6.2 completely (including its config), reinstalled it and font was saved correctly.

**Comment by stevenpusser** [comment] 2017-10-27 21:56
It's not an permission issue, since the app remembers other changes in the settings, and I can remove the fp.conf file and have it get re-created, but the font issue persists.  The "remember font" setting has no effect one way or the other.  Let me test your build.

**Comment by tsujan** [comment] 2017-10-27 22:21
> It's not an permission issue

Very strange! Because there's nothing special about the font settings.

> No, the Ubuntu deb has the same issue

It was among my tests on VirtualBox+Kubuntu LTS, as I mentioned above.

> Maybe it's something wrong with the MX iso.

I have no idea. Is the ISO image installed or is it running live?

**Comment by stevenpusser** [comment] 2017-10-27 22:36
It's running live in Virtual Box.  I just a test upgrade on an installed alpha 4 MX 17 from our previous 0.6.1+git version to the same exact 0.6.2 package that is having the problems on alpha 5, and  I don't see the issue at all.  I even deleted the fp.conf file to see if that made any difference.

**Comment by tsujan** [comment] 2017-10-27 22:58
I remembered that I had an old Debian Stretch on an old desktop computer (not updated for a year). I made an ugly deb package with `dh_make` and `dpkg-buildpackage -rfakeroot` for FeatherPad 0.6.2 there (I was surprised that it was compiled without problem), installed it and changed the font: the new font was remembered after closing and opening FeatherPad.

I think there may be a problem in the ISO.

**Comment by tsujan** [comment] 2017-10-28 05:36
2 questions:

(1) If you change the font while the current tab contains a text, will the font of that text change?
(2) Do other apps have problem with their font settings?

**Comment by stevenpusser** [comment] 2017-10-28 19:32
No, that's what is leading to the problem.  Testers are opening an existing text file on hdpi displays, and the default Deja Sans 9 is way too small, so they try to change the font and nothing happens.  They know that they can zoom with Ctl and the mouse wheel, but would like to change the default font.

Since it works the way it's supposed to on my installed test versions, perhaps that's because MX 17 has qt5 configured by default to follow XFCE's gtk2 and gtk 3 themes, and I disabled that so I could test kvantum and qt5ct on those installs. I will have to test that theory, but it would be a deal breaker if there isn't any workaround with those settings for qt5. The distro is going to be shipped with those settings.

**Comment by tsujan** [comment] 2017-10-28 19:58
> No, that's what is leading to the problem...

I didn't understand; was "No" the answer to question (1) or (2)? If the answer to (1) is "No", then something prevents fonts from changing and, most probably, the same problem should happen with other Qt5 apps too.

**Comment by tsujan** [comment] 2017-10-28 20:12
Ah, found the cause :)

I had a gnome-shell on another computer and, a few minutes ago, tried to change the font of FeatherPad thre but it didn't change. However, when I logged out from gnome-shell and logged into KDE or LXQt, the font was changed correctly. The reason is that KDE and LXQt can handle Qt5 font.

I'll try to find a workaround.

**Comment by tsujan** [comment] 2017-10-28 20:58
OK, I found and applied a workaround. V0.6.3 is released a few minutes ago just because of that workaround. It will definitely solves the problem of font setting under GTK environments.

If only you told me that the problem occurred under GTK DE's.... ;)

**Closed by tsujan** 2017-10-28 20:58 UTC
