### ISSUE TITLE
showCurrentLine to dark

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#147] opened 2018-05-12 23:39 UTC
If line numbers are on the current line is highlighted - cool feature, but in the light color scheme the lines are to dark and in the dark scheme vice versa - looks good at the beginning, but becomes pain in ass after a few hours. (ok, only my point of view)

**Comment by tsujan** [comment] 2018-05-13 02:02
I'll think about it; should experiment with other colors.

**Comment by agaida** [comment] 2018-05-13 10:37
Only Suggestions:
![new dark](https://i.imgur.com/RtZRwR2.png)

**Comment by tsujan** [comment] 2018-05-13 10:52
I've chosen a variable value based on the bg color, which is neither too mild nor too harsh. But will ask your opinion after making the commit.

**Comment by tsujan** [comment] 2018-05-13 11:04
Let me ask you before making a commit. Are these OK?

![1](https://user-images.githubusercontent.com/981076/39966551-0c091450-56c3-11e8-8dea-4606b090f400.png)
![2](https://user-images.githubusercontent.com/981076/39966553-119c50da-56c3-11e8-8cee-a5f6b71d62e4.png)

**Comment by agaida** [comment] 2018-05-13 11:11
ok, but if possible i would like the darker a bit darker and the lighter a bit lighter :) - as i said, i don't see a problem before, but yesterday was a bit extrem - used fpad in a approx. 11h session and after some hours it starts to disturb me.

**Comment by agaida** [comment] 2018-05-13 11:49
thats why i said the change should only be a bit - most of the time you have not only text lines and some empty space left - and the difference between normal and line-highlight should be so low as possible - that will make combinations with other highlights easier too

**Comment by tsujan** [comment] 2018-05-13 11:55
So, you mean the highlights in my screenshots are too mild. OK, I'll make them just a little stronger.

**Comment by agaida** [comment] 2018-05-13 11:56
no, the opposite :)

**Comment by tsujan** [comment] 2018-05-13 11:57
The opposite would be almost invisible and useless. I should think of another solution.

**Comment by tsujan** [comment] 2018-05-13 14:57
I tested with all kinds of underlines instead of highlights but they might make real underlines hard to see.

The problem is that the highlight should be suitable for all background values, which means, for example, different highlights should be used for different dark values from 0 to 50.  At last, I decided to use a linear formula which reduces the highlight intensity for the dark background of the above screenshot by 5 and is good for other dark values too.

I'll find a similar formula for light backgrounds. It seems that the eye stress can be fixed by using elementary algebra ;)

**Comment by agaida** [comment] 2018-05-13 16:28
right (bg_value +/- certain_value) can do wonders :D

**Comment by tsujan** [comment] 2018-05-13 16:56
> why not let the user decide about the certain value?

Because it's a function, not a value. Dark backgrounds go from 0 to 50 in FP, and for each value, a highlight intensity is needed. I set the highlight color to white and made its opacity a function of background value:
```c++
int opacity = -qRound ((qreal)(25 * bgColorValue) / (qreal)50) + 48;
```
Or simply: `opacity = 48 - 25  × bgColorValue / 50`.

With this, the opacity of the white highlight is 48 when the background is pitch black and is 23 when the background is `#323232` (the lightest dark color in FP). We can't expect from the user to set those two limits. I found them by trial and error and think nothing better could be done.

The result when the dark background value is 15:

![3](https://user-images.githubusercontent.com/981076/39969557-d30656d8-56f2-11e8-9628-d8ad1a543a6e.png)

The above highlight is hardly visible when seen inside a browser but it's visible when the user's eyes are accustomed to the black color. As a precaution, I also colored the number of current line (red, in this case).

**Comment by tsujan** [comment] 2018-05-13 16:59
Still a mark may be needed on the numbers panel when the line is wrapped -- like in the above screenshot -- but that's tricky.

**Comment by agaida** [comment] 2018-05-13 17:02
put a asterix in front of the line no? or some other bullet?

**Comment by tsujan** [comment] 2018-05-13 17:07
> put a asterix in front of the line no? or some other bullet?

Exactly! An asterisk, a bullet or a + sign; that's my plan. The only remaining thing is how to it ;)

**Comment by agaida** [comment] 2018-05-13 17:09
i know

**Comment by tsujan** [comment] 2018-05-13 17:11
Actually, I found a way a few minutes ago, but only inside my head :D Should try it.

**Comment by tsujan** [comment] 2018-05-13 18:04
A question: Does highlighting of current line have any use when this is possible?

![5](https://user-images.githubusercontent.com/981076/39970240-6bea7668-56fd-11e8-91dc-5cda10bd1c16.png)

I mean can I remove the highlight or is it helpful in some way?

**Comment by agaida** [comment] 2018-05-13 19:58
hmm - i would decouple line numbering and highlighting - and i don't think that hightlighting of only parts of a line is useful. In my sample only was short lines - but in some cases even symbol lines are really long - up to 200-300 chars. So it is nice to have the current line highlighted - esp if one is in diffs or in minified files. the other thing will be addressed by a better visible text-cursor

**Comment by tsujan** [comment] 2018-05-13 20:13
> but in some cases even symbol lines are really long - up to 200-300 chars. 

The line numbers pane would show that all of those lines belong to the same paragraph (= real line = block). Actually, a glance at the pane would be enough.

The problem with a line highlighter is exactly what you described here and I accepted as an issue. Only a very mild highlighter may circumvent the issue but, in that case, it wouldn't be easily visible.

Anyhow, after adding an underline to the current line number (for color blind users) , I'll keep the highlighter of current line but will make it as mild as you suggested above.

**Comment by tsujan** [comment] 2018-05-14 14:18
Done in https://github.com/tsujan/FeatherPad/commit/7437800022a94bde428839f665658b15e033b47e

Now, the current line highlighter is very mild, so that it doesn't interfere with text editing. The sign `↳` clearly shows to which line/block a wrapped line belongs, so that the job of line highlighter is done by the line number strip (pane).

**Closed by tsujan** 2018-05-14 14:18 UTC

**Comment by tsujan** [comment] 2018-05-14 14:27
I'll also make a small change to the line number strip minutes later.
