### ISSUE TITLE
Weak/unstable focus on side pane without search-bar

### ISSUE THREAD

**Issue by aramazano** [tsujan/FeatherPad#126] opened 2018-04-26 06:07 UTC
This also seems to be introduced by 0.9~28-g3ab4ca3-1

Clicking on one of the files in the side pane doesn't suffice to transfer keyboard focus to side pane, but double clicking does it. However, the focus duration is only for a single [Up] or [Down] keypress.

To reproduce:

1. Open several files in side pane mode.
2. Single-left-click on one of them.
3. Press [Up] or [Down] arrow key --> Instead of moving about within the side pane, cursor in the file being edited will move up and down
4. Double-click on one of the files in side pane.
5. Press [Up] or [Down] arrow key *once* --> selection in the side pane will move one file up or down.
6. Press [Up] or [Down] arrow key *once again* --> Same as (3) - side pane focus is lost.

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~13-gb5ddbd4-1
* qtermwidget Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* FeatherPad version: 0.9~28-g3ab4ca3-1

**Comment by tsujan** [comment] 2018-04-26 14:42
Cannot confirm this. In step 3, the item selection is changed, as expected. As a matter of fact, nothing is changed in the side-pane code.

BTW, although I'm an LXQt member, FeatherPad doesn't belong to LXQt and you don't need to add any info about LXQt here. The FeatherPad version is enough.

**Comment by tsujan** [comment] 2018-04-26 17:30
@aramazano I can't reproduce this with Fusion, Breeze or Kvantum and really think it isn't related to FeatherPad.

What happens when you click on a side-pane row other than the one related to the current page? Will its page be shown or do you need to double click it for that? Maybe, somehow, your global Qt settings is so that view-items are selected with double-clicking, instead of single-clicking.

**Comment by aramazano** [comment] 2018-04-26 20:49
> What happens when you click on a side-pane row other than the one related to the current page? Will its page be shown or do you need to double click it for that?

@tsujan the page changes properly, everything works as expected, except keyboard focus is not transferred to the side pane. Focus only transfers if double clicked, but lives only for a single Up/Down key-press, then it is again transferred back to the main window.

I did some more tests and confirmed that also pcmanfm-qt side panel exhibits the exact same behavior. So this is apparently not related to featherpad nor pcmanfm-qt, but should have something to do with Qt or some LXQt base component.

I have pretty default Qt and LXQt setup, so I don't know why it is affecting just me. @agaida if you have a Debian LXQt environment handy, could you test this as well?

I don't know which Qt library or component is responsible for side panes, but here are several key Qt components I currently have installed:

ii  libqt5core5a		5.10.1+dfsg-5
ii  libqt5gui5			5.10.1+dfsg-5
ii  libqt5quickwidgets5		5.10.1-4
ii  libqt5widgets5		5.10.1+dfsg-5
ii  libqt5x11extras5		5.10.1-2

Hopefully the problem may go away by itself with newer versions of Qt.

**Comment by tsujan** [comment] 2018-04-26 20:57
In the case of pcmanfm-qt, that's PCMan's design and is expected. In the case of FeatherPad, it's very strange! If it was a Qt issue, I should be able to reproduce it because we have the same version of Qt5; however, it doesn't happen here.

Although I closed this, I'll think about it until I find the cause. Even if it's really a Qt issue, a workaround might be possible.

Until then, if it disappears with a Qt update in Debian, I'd be grateful if you tell me (I don't have Debian).

**Comment by aramazano** [comment] 2018-04-26 21:01
> Until then, if it disappears with a Qt update in Debian, I'd be grateful if you tell me (I don't have Debian).

I will keep an eye on it and update you about it if anything changes.

**Comment by aramazano** [comment] 2018-04-26 21:15
BTW it is such a minor bug that I don't feel it deserves a special workaround if it is a Qt issue. It can even be considered as a "peculiar" feature. :)

**Comment by agaida** [comment] 2018-04-26 21:18
@aramazano - nope - even so called minor bugs have ~can~ will bite you hard at the worst moment in the worst of all scenes. That's what the most folks call Murphy's Law.

**Comment by agaida** [comment] 2018-04-26 21:28
no - i can't reproduce it right now - but i remember some similar glitches. And if it is reproducible for @aramazano i would like to see it with my own eyes. In former times we had such things like teamviewer and similar things to so so (Professional ERP programming and support :) ) - In the Linux universe these tools aren't used that much.

**Comment by tsujan** [comment] 2018-04-26 21:32
I used teamviewer  for fun a long time ago but yes, it was a powerful tool.

**Comment by aramazano** [comment] 2018-04-26 21:37
An observation: When focus is on the side pane (by doubleclick) then only the keys that change selection on side pane (Up, Down, Home, End, PgUp, PgDn) is transferring the focus back to main view. And those keys, while changing the selection on side pane, are also updating the main view so that main view now starts showing the newly selected file's content.

I feel that this change of main view content may have an effect on focus transfer. Just a vague guess.

**Comment by agaida** [comment] 2018-04-26 22:34
@aramazano - plain no :) - the only things that are sensible in that regard are all packages that depend on Qt private symbols - featherpad use none of them.

Next - how debian works - the short version: Packages enter in Sid, be there some time and are migrated to testing after some days - if no bad things happend. Without recompiling - so it is perfectly fine to use repositories that are compiled with sid. You are using only things that are compiled in sid :d even if you are using testing - the only difference is that the bugs are more mature :P

**Comment by agaida** [comment] 2018-04-26 22:38
```
% apt policy qtbase5-dev
qtbase5-dev:
  Installiert:           5.10.1+dfsg-5
  Installationskandidat: 5.10.1+dfsg-5
  Versionstabelle:
 *** 5.10.1+dfsg-5 500
        500 http://ftp.debian.de/debian testing/main amd64 Packages
        500 http://ftp.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```
you can do this with all lxqt dependencies - the result should be the same

**Comment by tsujan** [comment] 2018-04-26 22:43
> the only things that are sensible in that regard are all packages that depend on Qt private symbols - featherpad use none of them.

Completely right. No private header, no headache.

**Comment by aramazano** [comment] 2018-04-26 23:05
> you can do this with all lxqt dependencies - the result should be the same

I know. And I use apt-cache policy checking quite a lot. So Testing and Sid are the same to a large extent, but there is always some odd package, sometimes here sometimes there, waiting to be migrated to Testing. This results in sparse, spurious and temporary version mismatches between some Sid and Testing packages. I can't policy check the whole recursive dependency tree at each upgrade, so I am completely depending on dependency resolution to work this chore out. 

This is my general approach. As for private symbols vs FeatherPad, I am glad to learn that, so I don't need to worry about using experimental-FP against Testing base.

Also thank you for pointing out "apt build-dep" I am inspecting it. Also installing dev packages to compile/install FP locally as per tsujan's recommendation. I will update the thread about results.

**Comment by tsujan** [comment] 2018-04-26 23:14
> Also installing dev packages to compile/install FP locally as per tsujan's recommendation

Don't *install* it; just compile and test it. Always use deb packages for installation on Debian. Sorry if I said something that was obvious to you!

**Comment by agaida** [comment] 2018-04-26 23:25
the meaning of arch or manjaro testing is far right from debian/experimental ...
in the sense of oldstable -> stable -> testing -> unstable -> experimental   ..... -> arch testing

**Comment by tsujan** [comment] 2018-04-26 23:31
Manjaro testing is like Debian sid -- which is a stable Debian -- and sometimes it has versions found in experimental.

I can't compare Manjaro to Debian; Debian is what it advertises: the universal operating system. Its power can't be found in other distros. However, I didn't need its full power. What I needed was a fast and easy-to-use package manager. That's the only weak point of Debian, IMO.

Let's not talk about Debian; I don't want to get nostalgic and install it ;)

**Comment by agaida** [comment] 2018-04-26 23:47
you should try siduction LXQt (the paintitblack edition) - you would be surprised - and it is a live iso, so it must not be installed :D 
https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201804262335.iso
https://isobuilds.siduction.org/lxqt/amd64/siduction-18.3.0-paintitblack-lxqt-amd64-201804262335.amd64.manifest

**Comment by agaida** [comment] 2018-04-26 23:55
Shameless self promotion (all out of the box)
systemd:  Installed: 238-4
featherpad:  Installed: 0.9~29-gccdb2f5-1
Linux tester-pc 4.16.5-towo.1-siduction-amd64 #1 SMP PREEMPT siduction 4.16-12 (2018-04-26) x86_64 GNU/Linux

**Comment by tsujan** [comment] 2018-04-26 23:55
Ah, I loved those live isos, which ones could create from one's own system: remastering :)

**Comment by aramazano** [comment] 2018-04-26 23:56
Well, embarrassed to ask such a dumb question, but...

Downloaded zip-ball from github, unpacked it, installed all the build dependencies for Debian as per INSTALL file (even installed libqt5svg5-dev though not mentioned) and then,

.../FeatherPad-master-i427$ qmake && make
qmake: could not find a Qt installation of ''

.../FeatherPad-master-i427$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

Did it both as a regular user and root : same result.

What could I be doing wrong here?

**Comment by agaida** [comment] 2018-04-26 23:56
nope - not remastered - pyfll is the keyword - it falls out of a clean build chroot -  it would be a regular release build if not the snapshots were integrated

**Comment by agaida** [comment] 2018-04-27 00:01
@aramazano - nearly all - if in rome do as the romans do
https://salsa.debian.org/lxqt-team/ - i would start here and clone the package i want to
next step: checkout experimental-snapshots
next step: git snapshot to get the current git sources
install debhelper, devscripts and lxqt-build-tools with apt - you are now ready to go
apt build-dep $foo;; debuild

**Comment by tsujan** [comment] 2018-04-27 00:01
> Did it both as a regular user and root : same result.

I highly recommend no doing anything as root, unless you want to install from the source and that only at the last stage, i.e., `sudo make install` (not recommended either).

> ibqt5svg5-dev though not mentioned

Oh, I should add it to the INSTALL info.

> What could I be doing wrong here?

Have no clue.

**Comment by tsujan** [comment] 2018-04-27 00:03
@agaida BTW, Whatever deb package that includes `QSvgRenderer` is a dependency since the last version.

**Comment by agaida** [comment] 2018-04-27 00:03
the nice thing about using distribution tools to do things is that the outcome is reproducible in the sense of settings etc - ok, for really reproducible results one should use pbuilder or sbuild instead of cmake .; make

**Comment by agaida** [comment] 2018-04-27 00:04
QSvgRenderer - for what?

**Comment by tsujan** [comment] 2018-04-27 00:06
The hard-coded SVG icons are an essential part of FeatherPad; they change color against dark/light backgrounds because a beautiful code I took from Cantata (simplified it a lot).

**Comment by tsujan** [comment] 2018-04-27 00:08
OK, it's `libqt5svg5-dev`. It's a dependency.

**Comment by tsujan** [comment] 2018-04-27 00:09
Sorry, I meant a *build* dependency. My bad!

**Comment by agaida** [comment] 2018-04-27 00:12
https://salsa.debian.org/lxqt-team/featherpad/blame/debian/sid/debian/control

**Comment by tsujan** [comment] 2018-04-27 00:13
Again, you reply less than a minute before me ;) Yes, I saw it right now.

**Comment by agaida** [comment] 2018-04-27 00:16
i had an advantage - wrote the packaging and had only to click onto the link

**Comment by tsujan** [comment] 2018-04-27 02:38
Quoting from INSTALL:

"If your default Qt installation is not Qt5, put the full path of Qt5 qmake in the first command but before that, put the full path of Qt5's "lrelease" binary into 'featherpad/featherpad.pro' (only one place)."

It was the case for you without `qt5-default` under Debian.

Thanks for the info! I'll add them to INSTALL.

P.S. I made FeatherPad when I used Debian but took `qt5-default` for granted. Debian Qt maintainers should do something about such problems. For example, Qt should depend on `qt5-default`, IMO.

**Comment by aramazano** [comment] 2018-04-27 02:39
For the sake of completeness,

* Executed the compiled binary after shutting down any FeatherPad instance and checking with `ps`

* Executed compiled binary by `./featherpad` so I am sure I didn't accidentally run the installed version.

**Comment by tsujan** [comment] 2018-04-27 02:40
> Now back to the original problem: Executed the compiled binary and the problem is still the very same. I am lost at this point as I don't know why it is just me.

Impossible! Perhaps, you didn't download the latest git source from here.

**Comment by aramazano** [comment] 2018-04-27 03:16
Another observation: In order to pass keyboard focus to side pane, it is not necessary to "doubleclick" on a file in side pane, but it is enough to **click twice**.

That is, when I single-click on any file, that file is highlighted and its contents is shown in the main view. At this point, keyboard focus is still at the main view. But when I click again to this already highlighted file after a second (so it is definitely not a "doubleclick") the intensity of highlight subtly changes (turns from bright-white-on-blue to dull-white-on-blue) and at this point keyboard focus is transferred to side pane.

Then it is the same story: When I press Up or Down arrow, side pane highlighting and main view context switches to the neighboring file, but highlight intensity changes back to bright-white-on-blue concurrently with keyboard focus passing over to main view.

So, bright or dull highlighting directly correlates to keyboard focus at main view (bright white highlight) or side pane (dull white highlight), respectively.

I don't know whether bright or dull white text (on blue) highlighting means anything. Just sharing an observation FWIW.

**Comment by tsujan** [comment] 2018-04-27 03:25
So strange! Could you please attach 2 screenshots, one for each highlight state? Please also tell me which Qt style (Fusion, Breeze,...), Window Manager (KWin, Openbox,...) and compositor (KWin, Compton, Compiz,.., if any) you use.

**Comment by aramazano** [comment] 2018-04-27 04:02
I am attaching the screen shots. Note that in the bright-white-on-blue pic (i.e. focus on main view) the cursor is visible in the main view, whereas in the other pic (focus is on side pane) cursor is invisible.

I am running a fairly default LXQt here with the exception that I changed LXQt theme to "Light" (it was "Frost" by default if I remember correctly).

On a side note:
BTW @agaida I would suggest Light theme by default, as it is a cleaner theme better suited as a starting point for newcomers IMHO. Actually, original Frost or Dark theme had some usability problem that I forgot now (some icons not visible or something like that) Dark and otherwise "strong" themes are better suited for experienced users looking to fine tune their environment.

My current setup is;
* Style: Fusion (options: fusion, windows)
* Icon theme: Oxygen (options: oxygen, gnome, tango, highcontrast, adwaita)
* LXQt theme: Light (options: light, system, kde-plasma, frost, dark, ambiance)
* Window Manager: xfwm4
* Compositor: None (not installed one at all)

![bright-white-on-blue](https://user-images.githubusercontent.com/34963702/39344050-e45c09bc-49e8-11e8-8994-c8e6d577e266.png)
![dull-white-on-blue](https://user-images.githubusercontent.com/34963702/39344057-ec6b1f44-49e8-11e8-8c18-f9e8402ea90d.png)

**Comment by tsujan** [comment] 2018-04-27 04:54
Fixed in https://github.com/tsujan/FeatherPad/commit/bb9ee0cce483fb41cbab8dd576adb9a7ed8ad11b (which was for another thing) by changing just one line of code. That line had been written before side-pane and I forgot to change it afterward.

**Closed by tsujan** 2018-04-27 04:54 UTC
Labels: bug

**Comment by agaida** [comment] 2018-04-27 07:47
https://salsa.debian.org/lxqt-team/featherpad/blob/debian/sid/debian/rules

Setting QT_SELECT instead of makeing QT5 default would help too - or qmake -5 or .qt5 or so should help too.
