### ISSUE TITLE
segmentation fault error 

### ISSUE THREAD

**Issue by juppytt** [tsujan/FeatherPad#664] opened 2022-07-22 10:15 UTC
Hi, I get a segmentation fault (NULL dereference) on FeatherPad version 1.3.0. 
The error occurs when featherpad is in replacement mode (by pressing Ctrl-R) and gets SIGTERM or SIGQUIT by `pkill`.  
The backtrace is as follows.
I'm using Qt v5.15.2.

```
#0  0x00000000004b12a5 in FeatherPad::FPwin::removeGreenSel() ()
#1  0x00000000004b1b0d in FeatherPad::FPwin::closeReplaceDock(bool) ()
#2  0x00007ffff645f3e7 in QtPrivate::QSlotObjectBase::call (this=0x7a6770, r=0x61ec20, a=0x7fffffffd400) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#3  0x00007ffff64a44cc in doActivate<false> (sender=0x705cd0, signal_index=10, argv=0x7fffffffd400) at kernel/qobject.cpp:3886
#4  0x00007ffff649d591 in QMetaObject::activate (sender=0x705cd0, m=0x7ffff7b472a0 <QDockWidget::staticMetaObject>, local_signal_index=3, argv=0x7fffffffd400) at kernel/qobject.cpp:3946
#5  0x00007ffff754c9bd in QDockWidget::visibilityChanged (this=0x705cd0, _t1=false) at .moc/moc_qdockwidget.cpp:308
#6  0x00007ffff754bac4 in QDockWidget::event (this=0x705cd0, event=0x7fffffffd8f0) at widgets/qdockwidget.cpp:1520
#7  0x00007ffff73b533d in QApplicationPrivate::notify_helper (this=0x5c60c0, receiver=0x705cd0, e=0x7fffffffd8f0) at kernel/qapplication.cpp:3632
#8  0x00007ffff73b5129 in QApplication::notify (this=0x7fffffffdcc8, receiver=0x705cd0, e=0x7fffffffd8f0) at kernel/qapplication.cpp:3582
#9  0x00007ffff644c827 in QCoreApplication::notifyInternal2 (receiver=0x705cd0, event=0x7fffffffd8f0) at kernel/qcoreapplication.cpp:1063
#10 0x00007ffff644d2c4 in QCoreApplication::sendEvent (receiver=0x705cd0, event=0x7fffffffd8f0) at kernel/qcoreapplication.cpp:1458
#11 0x00007ffff74033b5 in QWidgetPrivate::hideChildren (this=0x5d7da0, spontaneous=false) at kernel/qwidget.cpp:8205
#12 0x00007ffff7402605 in QWidgetPrivate::hide_helper (this=0x5d7da0) at kernel/qwidget.cpp:7947
#13 0x00007ffff7402ec0 in QWidgetPrivate::setVisible (this=0x5d7da0, visible=false) at kernel/qwidget.cpp:8132
#14 0x00007ffff74029ba in QWidget::setVisible (this=0x61ec20, visible=false) at kernel/qwidget.cpp:8043
#15 0x00007ffff74024b6 in QWidget::hide (this=0x61ec20) at kernel/qwidget.cpp:7916
#16 0x00007ffff740366d in QWidgetPrivate::close_helper (this=0x5d7da0, mode=QWidgetPrivate::CloseNoEvent) at kernel/qwidget.cpp:8248
#17 0x00007ffff73ee68a in QWidget::~QWidget (this=0x61ec20, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1468
#18 0x00007ffff7590446 in QMainWindow::~QMainWindow (this=0x61ec20, __in_chrg=<optimized out>) at widgets/qmainwindow.cpp:377
#19 0x000000000046c999 in FeatherPad::FPwin::~FPwin() ()
#20 0x000000000044f19d in FeatherPad::FPsingleton::~FPsingleton() ()
#21 0x000000000044e3f4 in main ()
```

**Comment by tsujan** [comment] 2022-07-22 10:24
Thank you very much for the report and the backtrace! I'll investigate it soon.

**Comment by tsujan** [comment] 2022-07-22 12:11
OK, this is caused by a Qt bug that has been fixed in Qt6. That explains why I couldn't reproduce it here, until I recompiled FeatherPad against Qt5.

I added a workaround for it in https://github.com/tsujan/FeatherPad/commit/7a8c80a49fd4a6da1ea218c1c191fb0aae7bdf20

Will release 1.3.1 soon.

**Closed by tsujan** 2022-07-22 12:11 UTC
