### ISSUE TITLE
Add Color scheme support

### ISSUE THREAD

**Issue by dayflip** [tsujan/FeatherPad#5] opened 2016-09-20 23:15 UTC
As of right now. The background can only be change by the widget theme set by kde or gtk. But this does not change the default color scheme. Witch can only work will with a white background. My guess will be to used QML or lxqt qss style for making the layout. As for programming this in to make this work. I have no clue. But it will be nice to to see. Add a little more flexibility to the work flow. And it can make it easier to use at night.

**Comment by tsujan** [comment] 2016-09-21 01:45
First, thank you for your suggestions!

By color scheme, do you mean the text-view color or the syntax highlighting colors?

FeatherPad’s text-view is white when the Qt theme is light but the color changes to “#ececec” with dark Qt themes (to avoid a very high contrast).  I like and use dark widget themes but they can cause problems in text-views, mostly when syntax highlighting is enabled.

I hesitated to add an option for color scheme of syntax highlighting because I wanted FeatherPad to be as light as possible with its more important features. However, I may experiment with it to see if it really adds to the “weight”. In that case, I’ll do so in the code and without QML (I dislike QML for its styling issues I encountered when writing Kvantum).

The other elements of FeatherPad should follow the Qt widget style but I made an exception for icons: It can use its own icons or the themes icons (→ Preferences dialog). That’s for GTK environments or the root instance.

**Comment by dayflip** [comment] 2016-09-21 23:12
Color scheme similar to terminal color scheme. Be able to change the background color and main text color. As will change the highlighting color. This way people make color scheme of their choice. I understand that this is aim to be light as possible. Using widget style is good way at going. But limited at white background on where it stand with highlighting enable.

Since you don't like QML. qss is much simpler to make changes or have a simple plain text config.

**Comment by tsujan** [comment] 2016-09-22 06:24
There's no problem on the coding level. The problem is how the user could choose colors. Because of syntax highlighting, we’re dealing with *lots* of colors here -- colors for comments, quotes, URLs, Qt methods, functions, keywords, XML blocks, XML attributes, diff files, log files, bracket selection, etc. So, it’s not just a matter of simple text and its background.

Perhaps the solution is a color dialog like that of Kate. Or maybe I should add a set of predefined light and dark schemes for simplicity's sake (this is more acceptable, like in Qt Creator). I’ll think about it...

**Comment by tsujan** [comment] 2016-09-22 17:18
Added a clean dark color scheme and an option for choosing it to Preferences → Text (https://github.com/tsujan/FeatherPad/commit/2966dc973294bbedd0951d0e9e9ed24a61c590bb).

An option for *creating* color schemes didn’t seem wise to me because making a readable scheme could be a hard task and would interfere with usability -- finding a readable dark scheme wasn’t easy for me either.

**Comment by dayflip** [comment] 2016-09-22 22:58
in "highlighter.cpp". line 1445 blockFormat.setForeground (Violet);//d556e6. I remove //d556e6. Recompile. And this some how drop my memory used by 7MiB

**Comment by tsujan** [comment] 2016-09-22 23:10
> in "highlighter.cpp". line 1445 blockFormat.setForeground (Violet);//d556e6. I remove //d556e6. Recompile. And this some how drop my memory used by 7MiB

That's simply impossible; `//d556e6` is just a (redundant) comment. That 7Mib of memory couldn't be related to FeatherPad.

> The dark color scheme is nice

I'm glad you like it!

So, I close this issue. Feel free to add any relevant comment to it! And thanks again for the suggestion!

**Closed by tsujan** 2016-09-22 23:10 UTC
Labels: enhancement

**Comment by tsujan** [comment] 2016-09-22 23:12
Edit: FeatherPad uses ~ 7Mib of memory here too. What I meant above was that the removal of that comment couldn't have any effect.

**Comment by bcoolumbo1** [comment] 2019-07-29 07:34
What about pastell colors for background when using custom themes that are NOT dark?
My color for text entries is #D4FAE9 for my favorite mint/sea green theme.
#D4FAF7 would fit with blue themes and so on. Thank you.

**Comment by tsujan** [comment] 2019-07-29 12:05
@bcoolumbo1 
The current fg/bg colors are chosen with care, so that everything is clearly visible. If I add custom colors, I'll also make the background color optional and add this warning to the GUI: "**Changing these colors can easily damage visibility!**"

Please also see https://github.com/tsujan/FeatherPad/issues/145#issuecomment-478556544 for why I haven't done it yet.
