### ISSUE TITLE
Sel. Chars is always 0

### ISSUE THREAD

**Issue by internet-police** [tsujan/FeatherPad#742] opened 2023-05-29 14:24 UTC
Heyo
just wanted to let you know that the function to show how many characters are selected is not working properly
it always says 0

Greetings!

**Comment by tsujan** [comment] 2023-05-29 14:37
Not reproducible. Here, the number of selected characters is always shown correctly, whether with Qt5 or with Qt6.

You didn't provide any info about the version or how you installed the app, but if you have a very old version, please upgrade.

**Comment by internet-police** [comment] 2023-05-29 16:01
i am using the latest version 1.4.0
build from source on debian 11 with qt5

**Comment by tsujan** [comment] 2023-05-29 16:24
There should be some hidden factor in your case. Don't forget to add comment if you find it.

![selected_chars](https://github.com/tsujan/FeatherPad/assets/981076/b753eb9f-9d45-4558-a43a-361ea1cdff56)

**Comment by tsujan** [comment] 2023-05-29 16:28
Found it! It happens when the option for selection highlighting isn't checked. It's a bug.

**Comment by tsujan** [comment] 2023-05-29 17:36
Fixed in https://github.com/tsujan/FeatherPad/commit/16a90876264824eb94df6c6d42faebaa35543d36

I should make a release because of this and some other changes in git.

Thanks a lot for the report!

**Closed by tsujan** 2023-05-29 17:36 UTC
Labels: bug
