### ISSUE TITLE
Problem using font selection menu

### ISSUE THREAD

**Issue by scottfurry** [tsujan/FeatherPad#345] opened 2020-01-20 00:59 UTC
Environment:
compiler: GCC 9.2.1
Qt: 5.12.5
CMake: 3.16.1
Linux: 4.19.87_p1-debian-sources-lts
Distro: Funtoo 1.4 release (gentoo derivative)
CPU: AMD Bulldozer
--- edit ---
version latest commit - 8eb4cfd8

Build via CMake did not produced any error conditions or warnings. (FYI build statement can be reduced to (`cmake -H. -Bbuild; make -C build` <- note: no cd'ing of folders required - see [here](https://cgold.readthedocs.io/en/latest/glossary/-B.html) ).

Start up did not produce any warnings. However, when selecting `Options`->`Font` and attempting to select the Font Family drop down list box, these warnings were produced:
```
Failed to compute left/right minimum bearings for "cursor.pcf"
Failed to compute left/right minimum bearings for "deccurs.pcf"
Failed to compute left/right minimum bearings for "decsess.pcf"
Failed to compute left/right minimum bearings for "micro.pcf"
```
The sequence repeats when any of these items have mouse-over(i.e. mouse movement over an item) in the drop down list.
Checkbox "programming fonts" is enabled (default and unchanged from install).
Overall presentation of font list is rather large(assuming an application defined font size is used for the listing).
The files referenced could not be located on this system (`sudo find / -mount -type f -iname '*.pcf'` - no results).

**Comment by scottfurry** [comment] 2020-01-20 01:10
I should also note:
DE: xfce 4.12
using [Qt5 Configuration Tool](https://sourceforge.net/projects/qt5ct/) v 0.41
Theme Vertex Dark (available [here](https://github.com/horst3180/vertex-theme)

**Comment by tsujan** [comment] 2020-01-20 07:45
Thanks for taking time and reporting. Whether the problem you see is caused by `qt5ct` or by a corrupt file/installation (`xorg-fonts-misc`, for example), I don't know but it definitely isn't caused by FeatherPad and isn't reproducible here.

> Overall presentation of font list is rather large

A screenshot like the following might be helpful:

![font](https://user-images.githubusercontent.com/981076/72707566-f53f4c00-3b75-11ea-8d76-abf01579de96.png)

I close this but feel free to add comments -- I'll read them and reply.

**Closed by tsujan** 2020-01-20 07:45 UTC

**Comment by scottfurry** [comment] 2020-01-20 08:13
![font_menu_selection](https://user-images.githubusercontent.com/6686571/72709262-c9927680-3b21-11ea-81ec-d6ddbc8042e4.png)
Whether qt5ct is causing this is unclear. Theme coordination between GTK/Qt is a bit of mess overall. For completeness, attaching screen shot. Suspect default rendering may be relying too much on outside (or DE) settings.

**Comment by scottfurry** [comment] 2020-01-20 08:26
As for the suggestion of xorg-fonts-misc, gentoo calls it fonts-misc-misc. It was not installed originally but install did not improve situation. Re-installation of other fonts also did not improve circumstances.

**Comment by tsujan** [comment] 2020-01-20 08:29
If you search with Google, you'll find similar reports in other places too. Your installed `fontconfig` can also be the cause (just a guess because `fontconfig` had a problem in Arch a few months ago).

If I've correctly understood your report, the warnings don't prevent font changing. If so, you could ignore them.

BTW, nothing seems large to me in your screenshot: the monospace fonts that are installed on your system are listed (but that doesn't mean all of them are usable).

**Comment by scottfurry** [comment] 2020-01-20 08:34
I hadn't done a "google wide" search of problem as this the first time I have encountered this type of issue. Then again, most of the apps I've used that have font selection are gtk-based.

The showing of bitmap fonts (*.pcf) files that I can't find on my system is a bit confounding.

Overall, program is workable. There is a delay in the font drop down box (first series of error messages about *pcf files) that necessitates clicking down arrow twice before it responds. Only other knock I have is getting theme or foreground/background colours sorted out. There isn't a selector in the preferences which probably means I have to setup a css. :(

**Comment by tsujan** [comment] 2020-01-20 08:39
>  hadn't done a "google wide" search of problem 

The first result I got with Google: https://github.com/spyder-ide/spyder/issues/4035

> Only other knock I have is getting theme or foreground/background colours 

See `Preferences` → `Text` → `Dark color scheme` (and `Background color value`).

Syntax highlighting colors are also configurable in the latest git source. The feature will be in V0.13.0.

**Comment by tsujan** [comment] 2020-01-20 08:52
> There is a delay in the font drop down box (first series of error messages about *pcf files) that necessitates clicking down arrow twice before it responds.

There is a minor bug in Qt's "font combo-box" that causes the first delay. It happens with Qt styles (like gtk2, which you use) that show a pop-up menu instead of a drop-down lists. Fortunately, font changing isn't something users do very often.
