### ISSUE TITLE
Add support of FreeBSD (and DragonFlyBSD)

### ISSUE THREAD

**Issue by OlivierDuchateau** [tsujan/FeatherPad#8] opened 2016-10-15 20:33 UTC
Patch adds support of FreeBSD, otherwise compilation fails.

``` diff
From 0753b7ae71156d2fe842008af94a7ecd00770c1f Mon Sep 17 00:00:00 2001
From: Olivier Duchateau
Date: Sat, 15 Oct 2016 22:27:36 +0200
Subject: [PATCH] Add support of FreeBSD

---
 featherpad/encoding.cpp | 1 +
 featherpad/x11.h        | 3 ++-
 2 files changed, 3 insertions(+), 1 deletion(-)

diff --git a/featherpad/encoding.cpp b/featherpad/encoding.cpp
index dae9279..166eb18 100644
--- a/featherpad/encoding.cpp
+++ b/featherpad/encoding.cpp
@@ -8,6 +8,7 @@

 #include <stdlib.h> // getenv
 #include <langinfo.h> // CODESET, nl_langinfo
+#include <locale.h>
 #include <stdint.h> // uint8_t, uint32_t
 #include <QTextCodec>
 #include "encoding.h"
diff --git a/featherpad/x11.h b/featherpad/x11.h
index 9b015f6..1d470c1 100644
--- a/featherpad/x11.h
+++ b/featherpad/x11.h
@@ -18,9 +18,10 @@
 #ifndef X11_H
 #define X11_H

+#include <QtGlobal>
 #include <QList>

-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
 #include <X11/Xlib.h>
 #endif

-- 
2.10.1

```

**Comment by tsujan** [comment] 2016-10-15 20:51
Thanks!
Since I have no knowledge about FreeBSD, I should ask:

(1) Will the compilation be OK if those two headers (`locale.h` and `QtGlobal`) are added conditionally? I mean as:
````
#if defined Q_OS_FREEBSD
#include <locale.h>
#endif
````
and
````
#if defined Q_OS_FREEBSD
#include <QtGlobal>
#endif
````

(2) Does FeatherPad work OK under FreeBSD?

**Comment by OlivierDuchateau** [comment] 2016-10-16 10:14
```
#if defined Q_OS_FREEBSD
#include <locale.h>
#endif
```

The above conditional block is not necessary. locale.h defines LC_ALL macro (see glibc [1]), so on Linux you need this header too.

Then for the second, as I'm not Qt expert, I think it's also required, because the <QtGlobal> [2] header calls some macros, especially Q_OS_LINUX and Q_OS_FREEBSD, and I don't see this header in one of files of your project.

[1] https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=blob;f=locale/locale.h;h=2f85c6cfb17ae44c986ef971e532154ff41a617f;hb=fdfc9260b61d3d72541f18104d24c7bcb0ce5ca2#l41
[2] http://doc.qt.io/qt-5/qtglobal.html

**Comment by tsujan** [comment] 2016-10-16 11:13
On Linux, headers like `QtGlobal` and `locale.h` are included indirectly, through other headers, so there isn't any need to include them directly.

If FreeBSD is so different, I should try it on VirtualBox.

**Comment by OlivierDuchateau** [comment] 2016-10-16 12:04
I try your proposed patches:

```
#if defined Q_OS_FREEBSD
#include <locale.h>
#endif
```

It doesn't work. LC_ALL is not defined. It is worth to add this header globally?

Moreover QtGlobal header  is not necessary, so I improve support of FreeBSD.

```diff
From 7524772ec84875b267ebdf55f586c03d1eb7a0d5 Mon Sep 17 00:00:00 2001
From: Olivier Duchateau
Date: Sun, 16 Oct 2016 13:50:39 +0200
Subject: [PATCH] Add support of FreeBSD

---
 featherpad/encoding.cpp |  1 +
 featherpad/x11.cpp      | 10 +++++-----
 featherpad/x11.h        |  2 +-
 3 files changed, 7 insertions(+), 6 deletions(-)

diff --git a/featherpad/encoding.cpp b/featherpad/encoding.cpp
index dae9279..166eb18 100644
--- a/featherpad/encoding.cpp
+++ b/featherpad/encoding.cpp
@@ -8,6 +8,7 @@
 
 #include <stdlib.h> // getenv
 #include <langinfo.h> // CODESET, nl_langinfo
+#include <locale.h>
 #include <stdint.h> // uint8_t, uint32_t
 #include <QTextCodec>
 #include "encoding.h"
diff --git a/featherpad/x11.cpp b/featherpad/x11.cpp
index d801e3e..5a9d8e6 100644
--- a/featherpad/x11.cpp
+++ b/featherpad/x11.cpp
@@ -18,7 +18,7 @@
 #include <QString>
 #include "x11.h"
 
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
 #include <X11/Xatom.h>
 #include <QX11Info>
 #endif
@@ -35,7 +35,7 @@ long fromDesktop()
 {
     long res = -1;
 
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
     Display  *disp = QX11Info::display();
     if (!disp) return res;
 
@@ -70,7 +70,7 @@ long onWhichDesktop (Window w)
 {
     long res = -1;
 
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
     Display *disp = QX11Info::display();
     if (!disp) return res;
 
@@ -105,7 +105,7 @@ long onWhichDesktop (Window w)
 
 bool isWindowShaded (Window window)
 {
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
     Display *disp = QX11Info::display();
     if (!disp) return false;
 
@@ -140,7 +140,7 @@ bool isWindowShaded (Window window)
 /*************************/
 void unshadeWindow (Window window)
 {
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
     Display *disp = QX11Info::display();
     if (!disp) return;
 
diff --git a/featherpad/x11.h b/featherpad/x11.h
index 9b015f6..29112a6 100644
--- a/featherpad/x11.h
+++ b/featherpad/x11.h
@@ -20,7 +20,7 @@
 
 #include <QList>
 
-#if defined Q_WS_X11 || defined Q_OS_LINUX
+#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD
 #include <X11/Xlib.h>
 #endif
 
-- 
2.10.1
```

**Comment by tsujan** [comment] 2016-10-16 13:41
Thank you for your tests! It'll be nice if FeatherPad works on BSD systems as well.

Adding `locale.h` doesn't cause any problem in Linux. So, if it's needed in BSD systems, I'll add it alongside `defined Q_OS_FREEBSD`.

I'd be very grateful if you do another test too. I'm curious to know that the automatic encoding detection works well in FreeBSD. Please download this text file and open it in FeatherPad:

https://dl.dropboxusercontent.com/u/7793460/%C3%9Cber%20Psychoanalyse%20F%C3%BCnf%20Vorlesungen.txt

Then go to `File` menu and click `Document Properties`! Is the encoding `ISO-8859-1` on the statusbar?

**Comment by OlivierDuchateau** [comment] 2016-10-16 15:28
If I try to open Über Psychoanalyse Fünf Vorlesungen.txt with FeatherPad, it can't open it (I don't know if it's Qt problem or FeatherPad). If I rename it (e.g., Vorlesungen.txt), FeatherPad works fine, and encoding is ISO-8859-1.

Globally, FeatherPad can't open file (or directories) with special characters.

I tried with another text editor, Mousepad, and encoding is right (with/without default name).

Note: On this machine (11.0-RELEASE-p1), UTF-8 is default encoding (since 10.3, UTF8 support was improved).

**Comment by tsujan** [comment] 2016-10-16 15:51
Many thanks! So, encoding is detected right under FreeBSD :)

> Globally, FeatherPad can't open file (or directories) with special characters.

Strange! Here, on Linux, it has no problem with special characters. It may be related to FreeBSD's Qt. What if you drag and drop a file with special chars in its name into FeatherPad's window?

BTW, I may have found a way to install FreeBSD+KDE on VirtualBox but it'll take some time and I don't know when I'll have enough time for it.

**Comment by tsujan** [comment] 2016-10-16 23:18
I downloaded the amd64 vhd image of FreeBSD-11.0 and booted it with VirtualBox. Then I installed Gnome3 because, according to my experience, if a Qt5 app works under Gnome3, it'll work everywhere. After that, I installed Qt-5.6.1.

I can confirm all of your findings. Your last patch is needed for compiling FeatherPad on FreeBSD.

However, I found that the problem with files whose names contain special characters is *not* caused by FeatherPad. My reason is the open-file dialog:

![special_chars](https://cloud.githubusercontent.com/assets/981076/19421705/073bc01c-9414-11e6-8b06-04a3de911e8d.png)


This is a standard Qt dialog, which FeatherPad uses (it isn't made by FP). So, either FreeBSD's Qt has a problem or a package is missing from our FreeBSD systems.

**Comment by tsujan** [comment] 2016-10-17 00:19
There's also another possibility: I'm missing something about Qt5 on FreeBSD ;)

**Comment by tsujan** [comment] 2016-10-17 00:24
OK, even Qt Creator has the same problem:

![creator](https://cloud.githubusercontent.com/assets/981076/19422194/2c67ee3e-941d-11e6-9f60-b443fa3ab318.png)

I think, with the above image, you could report a bug at FreeBSD.

**Comment by tsujan** [comment] 2016-10-17 02:48
**For reference:**

After wrestling with FreeBSD for hours, I found the cause: `QProcessEnvironment::systemEnvironment()` doesn't give a utf-8 string for "LOGNAME" in FreeBSD. The workaround is simple and consists of using `qgetenv` instead (as is commented in `main.cpp`).

I'll add a commit after some tests.

**Comment by OlivierDuchateau** [comment] 2016-10-17 07:11
I try with a pure Qt5 application (lximage-qt, taken from my LXQt repository) and Qt open dialog works fine. I don't know if there're differences (my favourite toolkit is rather Gtk+).

**Comment by tsujan** [comment] 2016-10-17 07:36
> I don't know if there're differences

It took me hours to know what's the difference (QProcessEnvironment).

Anyhow, the latest commit adds full support for BSD systems.

**Comment by tsujan** [comment] 2016-10-17 07:49
BTW, I don't know about bug reports in FreeBSD -- I installed it on VirtualBox just hours ago -- but if I was an active BSD user, I'd surely report the problem in the open-file dialog of Qt Creator. It could help them to make FreeBSD's Qt support better.

**Comment by tsujan** [comment] 2017-04-26 03:04
Closing this -- the support was added a long time ago.

**Closed by tsujan** 2017-04-26 03:04 UTC
